Lt 4035 price alerts
LykkeBusiness/Lykke.Snow.PriceAlerts pull request #1
Opened 2022-08-10 07:13 UTC by gponomarev-lykke

2022-08-23 19:48 UTC, tarurar requested changes

2022-08-23 19:48 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.DomainServices/Services/PriceAlertsService.cs
> +        public async Task<Result<PriceAlert, PriceAlertErrorCodes>> GetByIdAsync(string id)
Why not use `PriceAlertId` as part of service contract?

2022-08-23 19:48 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.DomainServices/Services/PriceAlertsService.cs
> +            var isUnique = _priceAlertsCache.IsUnique(priceAlert);
Such validation could be easily missed in further improvements and maintenance. Wouldn't it be more reasonable to implement the uniqueness using key value storage? So we guarantee the unique price alert on storage level, not on business logic level.

2022-08-23 19:48 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.DomainServices/Services/PriceAlertsService.cs
> +            if (priceAlert.Price <= 0)
I would make this validation first cause it is the cheapest one.

2022-08-23 19:48 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.DomainServices/Services/PriceAlertsService.cs
> +            if (!string.IsNullOrEmpty(priceAlert.Comment) && priceAlert.Comment.Length > 70)
Same here

2022-08-23 19:48 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.DomainServices/Services/PriceAlertsService.cs
> +            priceAlert.Id = new PriceAlertId();
You continue object construction here, which means most probably the object comes here (as a parameter) in invalid state. I'd avoid object construction segregation as much as possible. 
Another point - priceAlert is mutable, I'd consider make it immutable.

2022-08-23 19:48 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.DomainServices/Services/PriceAlertsService.cs
> +            var isActive = _priceAlertsCache.IsActive(id, out var cachedAlert);
Repeatable code most probably means you better have separate cache for active alerts only.

2022-08-23 19:48 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.DomainServices/Services/PriceAlertsService.cs
> +                alert.ModifiedOn = _systemClock.Now();
Are such modifications thread safe?

2022-08-23 19:48 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.DomainServices/Services/SystemClock.cs
> +            return DateTime.Now;
UtcNow?

2022-08-23 19:48 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.SqlRepositories/EntityConfigurations/PriceAlertEntityConfiguration.cs
> +            builder.Property(x => x.Comment).HasMaxLength(70);
I see the 70 integer literal at least for the second time. Probably, better use constant.

2022-08-23 19:48 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.SqlRepositories/Repositories/PriceAlertsRepository.cs
> +        private const string DoesNotExistException =
```suggestion
        private const string DoesNotExistExceptionMessage =
```

2022-08-23 19:48 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts/Projections/AccountProjection.cs
> +                await _priceAlertsService.CancelByProductIdAsync(productId, accountId);
Cancellation reason seems like "nice to have feature"

2022-08-30 08:14 UTC, gponomarev-lykke commented on contract/Lykke.Snow.PriceAlerts.Contract/Lykke.Snow.PriceAlerts.Contract.csproj
> +        <LangVersion>8.0</LangVersion>
I assumed the bank has analysis tools only for 8.0
If it is safe to use the latest version of c#, I can change it

2022-08-30 08:15 UTC, gponomarev-lykke commented on contract/Lykke.Snow.PriceAlerts.Contract/Models/Contracts/PriceAlertContract.cs
> +        public DateTime ModifiedOn { get; set; }
These fields are created on backend and always have to be filled on creation of price alerts. When a price alert is created, CreatedOn = ModifiedOn = DateTime.Now
If any updates are made, only ModifiedOn is updated

2022-08-30 08:17 UTC, gponomarev-lykke commented on contract/Lykke.Snow.PriceAlerts.Contract/Models/Responses/PaginatedResponseContract.cs
> +    public class PaginatedResponseContract<T>
Ok, which lib do you suggest? Lykke.Snow.Common? I think it makes sense to add something like Likke.Snow.Contracts and add contract-related types there.

2022-08-30 08:25 UTC, gponomarev-lykke commented on src/Lykke.Snow.PriceAlerts.Domain/Extensions/PriceAlertExtensions.cs
> +        public static bool SameAs(this PriceAlert alert, PriceAlert compare)
I'm not sure it makes sense to use it here. It is purely a business logic comparison, while `IEquatable<T>` also affects how the item is handled inside of generic collections.

2022-08-30 08:33 UTC, gponomarev-lykke commented on src/Lykke.Snow.PriceAlerts.DomainServices/Services/PriceAlertsService.cs
> +                alert.ModifiedOn = _systemClock.Now();
Yep I asked Alex to check the service under load, I think it might duplicate notifications. But at the moment we could not reproduce it.
I have an idea how to add a lock object to every PriceAlert like this:
- get alert from cache
- lock(alert.lockObject)
- check that alert is still active
- update the price alert, send notifications etc.

What do you think?

2022-08-30 08:34 UTC, gponomarev-lykke commented on src/Lykke.Snow.PriceAlerts.SqlRepositories/EntityConfigurations/PriceAlertEntityConfiguration.cs
> +            builder.Property(x => x.Comment).HasMaxLength(70);
Ok, will fix

2022-08-30 08:34 UTC, gponomarev-lykke commented on src/Lykke.Snow.PriceAlerts.SqlRepositories/Repositories/PriceAlertsRepository.cs
> +        private const string DoesNotExistException =
Ok

2022-08-30 08:35 UTC, gponomarev-lykke commented on src/Lykke.Snow.PriceAlerts/Projections/AccountProjection.cs
> +                await _priceAlertsService.CancelByProductIdAsync(productId, accountId);
You mean add an additional field to PriceAlert and save there the reason why it was triggered / cancelled etc?

2022-08-30 09:23 UTC, tarurar commented on contract/Lykke.Snow.PriceAlerts.Contract/Models/Responses/PaginatedResponseContract.cs
> +    public class PaginatedResponseContract<T>
Well, yes. Makes sense.

2022-08-30 09:28 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.Domain/Extensions/PriceAlertExtensions.cs
> +        public static bool SameAs(this PriceAlert alert, PriceAlert compare)
When you model a business object the point is that it always should behave as a domain model. The division on business behaviour and "technical" behaviour within single object only brings more anemic domain model issues. Up to you, ofc.

2022-08-30 09:29 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts.DomainServices/Services/PriceAlertsService.cs
> +                alert.ModifiedOn = _systemClock.Now();
Looks good.

2022-08-30 09:30 UTC, tarurar commented on src/Lykke.Snow.PriceAlerts/Projections/AccountProjection.cs
> +                await _priceAlertsService.CancelByProductIdAsync(productId, accountId);
Not sure it is worth adding into PriceAlert, looks like it is more relevant to placed into audit log or something.

2022-08-30 10:38 UTC, gponomarev-lykke commented on src/Lykke.Snow.PriceAlerts/Projections/AccountProjection.cs
> +                await _priceAlertsService.CancelByProductIdAsync(productId, accountId);
At the moment we do not have audit logs here, also as Vera explained - audit log is for support staff, and activities are for clients. I'll investigate if we can somehow pass it to Activities

2022-08-30 12:30 UTC, tarurar approved these changes

2022-08-30 12:56 UTC, merged